### ISSUE TITLE
documentation for JS tweaks

### ISSUE THREAD

**Issue by FekketCantenel** [notion-enhancer/tweaks#24]
Since there are no example Javascript tweaks in this repo, I've bumbled around writing my own keyboard shortcuts (Linux) in vanilla JS. I've included my `notion.js` below so you can get an idea of what needs to be documented.

* Is it possible to use jQuery/lodash/etc. in these tweaks?
* Currently the script is only executed when Notion loads. How can I write a script that executes on every page change (e.g. adding classes to headers)?
* I've been relying on `click()` mechanics because, as far as I know, there's no `notion()` API that I can access from these scripts. Do you know of one?

```
document.addEventListener('keyup', (e) => {
    if (e.key === 'Home' && !e.shiftKey) { /* Home: go to top of page */
        e.preventDefault();
        e.stopPropagation();
        if (document.querySelector('.notion-page-content') == null) {
            document.querySelector('.notion-page-controls').scrollIntoView(false);
        }
    }
  
    if (e.key === 'n' && e.altKey ) { /* ALT+N: new page */
        e.preventDefault();
        e.stopPropagation();
        document.querySelector('.notion-collection-view-item-add > .notion-focusable').click();
    }
    
    if (e.key === 'o' && e.ctrlKey ) { /* CTRL+O: open Find Page dialog */
        document.querySelector(".notion-sidebar div:nth-child(4) div:first-child").click();
    }
    
    if (e.key === '/' && e.ctrlKey ) { /* CTRL+/: search database */
        e.preventDefault();
        e.stopPropagation();
        document.querySelector(".notion-frame * .collectionSearch").parentNode.click();
    }
    
    if (e.key === '{' && e.ctrlKey) { /* CTRL+SHIFT+[: go back to database */
        document.querySelector(".notion-topbar-breadcrumb > .notion-collection_view_page-block > a").click();
    }
});

```

**Comment by dragonwocky** [comment]
> Is it possible to use jQuery/lodash/etc. in these tweaks?

the code in these tweaks runs in the global scope. you may use whatever is available there by default. from a quick test, it looks like that does include lodash but not jQuery.

> Currently the script is only executed when Notion loads. How can I write a script that executes on every page change (e.g. adding classes to headers)?

you would need to use a mutationobserver to listen and respond to changes to the page.

> I've been relying on click() mechanics because, as far as I know, there's no notion() API that I can access from these scripts. Do you know of one?

there is not.

---

JS inserts will not be documented because there is nothing to document. putting code in a JS script is equivalent to pasting it into the console.

the next release of the notion-enhancer will come with a powerful API that will include helpers for e.g. data persistence, keyboard shortcuts, page observers and interacting with a notion API - however, if you want to use it you will need to create a mod rather than a JS insert.
