### ISSUE TITLE
CSS for hiding "+new" button in gallery also hides "load more"

### ISSUE THREAD

**Issue by SaurPuss** [notion-enhancer/tweaks#25]
When using the following CSS provided by the examples:

```
.notion-gallery-view
  .notion-selectable.notion-collection_view-block
  div
  div
  + [role="button"],
.notion-gallery-view
  .notion-selectable.notion-collection_view_page-block
  div
  div
  + [role="button"] {
  display: none !important;
}
```

it hides the "load X more" option from the gallery view right along with the empty card.

![IMG_0247](https://user-images.githubusercontent.com/24640495/143872421-46304b68-a2bc-4b44-b014-2da0ed6c7b18.jpg)

**Comment by dragonwocky** [comment]
this repository is being archived & all issues are being closed in favour of a new tweaks page on the notion-enhancer website (coming soon)

this specific issue should also by solved by using the "simpler databases" extension (coming in v0.11.0) to hide the +new button instead of depending on this tweak
